apiVersion: v1
kind: Service
metadata:
  labels:
    app: site
  name: site
spec:
  ports:
    - port: 5151
      protocol: TCP
      targetPort: 80
  selector:
    app: site
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api
spec:
  ports:
    - port: 5152
      protocol: TCP
      targetPort: 3000
  selector:
    app: api
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: db
